### ISSUE TITLE
Race condition due to mix of start/restart logic

### ISSUE THREAD

**Issue by phvalguima** [canonical/opensearch-operator#154]
When running the `OpenSearchPluginManager`, it is failing to correctly restart all the nodes post-install / -configuration. The only node that reliably gets restarted is the leader unit. I am occasionally getting clusters that have not accounted for the newly installed `repository-s3` plugin (i.e. they did not restart after install). I can see the locks being required and then released, but journalctl does not show a restart at the same corresponding time.

The first thing is that we are using the `acquire_lock` event with 2x different types of callbacks: `_start_opensearch` and `_restart_opensearch`. Looking at RollingOps code, I can see it sets [the callback_override function at `acquire_lock.emit`](https://github.com/canonical/charm-rolling-ops/blob/7745ceee696007003485b6912ce01aae87ab0bed/lib/charms/rolling_ops/v0/rollingops.py#L388) and then, [it uses the method that was defined `at constructor time`](https://github.com/canonical/charm-rolling-ops/blob/7745ceee696007003485b6912ce01aae87ab0bed/lib/charms/rolling_ops/v0/rollingops.py#L401). That means we are always using `_start_opensearch`.

The first step is to get the charm to use a single callback. The `_restart_opensearch` is de facto choice, as it optionally stops the running opensearch service.

However, `_restart_opensearch` checks first if we have a `starting` flag set in the peer relation. That is important at the moment of the very first start, but after it can cause some deadlocks (e.g. the following `_start_opensearch` may set that flag and prematurely exit, before removing the flag, then no other _restart_opensearch calls will be able stop the service and no new configuration will be picked up).

The second step is to find a more suitable check to decide if we should stop the service.

The next issue: we are over-complexifying the `_restart_opensearch` by calling the `_start_opensearch` in it. The `_start_opensearch` [has multiple exits with a `defer`](https://github.com/canonical/opensearch-operator/blob/550b205ab99ec3e1b8416c95e736e0bd90ddb9a2/lib/charms/opensearch/v0/opensearch_base_charm.py#L601-L625). That effectively means we are deferring the RunWithLockEvent, which means potentially new restarts.

---------------------------------------------------------------------------------------------

I think there is a mix of tasks in this section of the code.

The start and restart should be distinct steps. Indeed, OpenSearch start can be very complex, if we consider large clusters; where we need a combination of `on_start`, `peer_joined` and `config_changed` events to trigger different information.

However, restart should be simple. The restart means the lock has been given to the unit and it must either do a restart quickly or pass the lock onwards to other units.

We should break the starting logic: to have a step-by-step that consciously start its unit manually, as the cluster is not yet set. Then, once that logic is finished, we can start calling the RollingOps to manage locks and restarts for us.

**Comment by Mehdi-Bendriss** [comment]
Is this issue still relevant / happening?

**Comment by phvalguima** [comment]
This was the early investigations that lead to `rolling-ops` bug. I think we can close this issue. There are others that are similar and I will close them as well.
