### ISSUE TITLE
[SHARDING][data-integrator] 1 or more 'replica' shards are not assigned, please scale your application up.

### ISSUE THREAD

**Issue by juditnovak** [canonical/opensearch-operator#172]
## Steps to reproduce

1. Run `data-integrator` Opensearch pipeline with 3 units

## Expected behavior
Tests pass

## Actual behavior

If 3 units are used in the test, I consistently keep getting the following [error](https://github.com/canonical/data-integrator/actions/runs/7616291365/job/20742821699#step:8:510), while the unit is stuck in a `blocked` state.
```
1 or more 'replica' shards are not assigned, please scale your application up.
```
The problem goes away when running the test with 2 units only.

## Versions

Operating system: jammy

Juju CLI: 

Juju agent: 3.2.2 

Charm revision: edge

## Log output

Juju debug log: see the pipeline referenced above 

## Additional context

I can't reproduce the issue locally. I executed the same pipeline multiple times on a powerful C5 AWS server. Passes green.
(May worth to do the same on a less powerful node too...?)

**Comment by phvalguima** [comment]
@dragomirp and I were looking into the `data-integrator` / opensearch issue a while back. @dragomirp were the issues with opensearch resolved, can we close this bug?

**Comment by Mehdi-Bendriss** [comment]
This is no longer occurring, OpenSearch tests on the data-integrator pass successfully. Health / Status reporting has been fixed in https://github.com/canonical/opensearch-operator/pull/279
