### ISSUE TITLE
[STABILITY] Opensearch service doesn't come up: Error: 503 Server Error: Service Unavailable for url: https://10.36.58.203:9200/_nodes

### ISSUE THREAD

**Issue by juditnovak** [canonical/opensearch-operator#219]
All details can be found on the pipelines where the issue occurs: 

- https://github.com/canonical/opensearch-dashboards-operator/actions/runs/8590250501/job/23537646297#step:21:1001

**Comment by Mehdi-Bendriss** [comment]
Closing as cannot reproduce this issue since https://github.com/canonical/opensearch-operator/pull/279
