### ISSUE TITLE
[STABILITY] Timeout awaiting service operation

### ISSUE THREAD

**Issue by juditnovak** [canonical/opensearch-operator#224]
All details available on the pipeline. The issue occured more than this two times.

- https://github.com/canonical/opensearch-operator/actions/runs/8630978165/job/23700888924#step:21:809
- https://github.com/canonical/opensearch-operator/actions/runs/8630978165/job/23696640136#step:21:831

**Comment by Mehdi-Bendriss** [comment]
Fixed in https://github.com/canonical/opensearch-operator/pull/279
