### ISSUE TITLE
[STABILITY] KeyError: 'results'

### ISSUE THREAD

**Issue by juditnovak** [canonical/opensearch-operator#225]
See corresponding pipelines.

 - https://github.com/canonical/opensearch-operator/actions/runs/8630978165/job/23703030624#step:21:1875
 - https://github.com/canonical/opensearch-operator/actions/runs/8630978165/job/23696640136#step:21:831

**Comment by Mehdi-Bendriss** [comment]
Fixed on https://github.com/canonical/opensearch-operator/pull/279
