### ISSUE TITLE
[BUG] `internal_users.yaml` is not syncronized across units

### ISSUE THREAD

**Issue by juditnovak** [canonical/opensearch-operator#246]
## Steps to reproduce
Start up a 2-members cham cluster and check with
`juju ssh opensearch/? sudo cat /var/snap/opensearch/current/etc/opensearch/opensearch-security/internal_users.yml` 

## Expected behavior

In order to safely switch leader anytime (potentially re-initializing the security index), these local users must be the same on all nodes.

Now what happens is: on the leader on `leader-elecetd` event we
 1. wipe out the `internal_users.yml` file
 2. add back the users that we need

This process has to run on all units.

**Comment by juditnovak** [comment]
More precisely: [this code](https://github.com/canonical/opensearch-operator/blob/main/lib/charms/opensearch/v0/opensearch_base_charm.py#L230-L243) is only executed on the leader, while it's supposed to be run on each unit.

**Comment by Mehdi-Bendriss** [comment]
Fixed in https://github.com/canonical/opensearch-operator/pull/216
