### ISSUE TITLE
Remove "non-charmed" user deletion at `update-status` and `client-broken`

### ISSUE THREAD

**Issue by phvalguima** [canonical/opensearch-operator#331]
Currently, we have `OpenSearchUserManager.remove_users_and_roles`, which removes users and roles that are not linked to system users or existing relations. [The removal happens here](https://github.com/canonical/opensearch-operator/blob/5174eed53acc0ba5a90da144e9ca0c16fd8c3da9/lib/charms/opensearch/v0/opensearch_users.py#L263-L264).

This method is called in two different places: [update status and client relation broken events](https://github.com/search?q=repo%3Acanonical/opensearch-operator%20remove_users_and_roles&type=code). Now, removing the relation user and role makes sense, but we should only remove that user / role, not a generic clean-up. We should also remove the call from `update_status`.

**Comment by Mehdi-Bendriss** [comment]
This is addressed as part of PR https://github.com/canonical/opensearch-operator/pull/342/files#diff-5c0d89f838ffd5a9ecf2288b3698320fda2d2b2b737361b6e10adb55d1929f43R622-R627 - essentially only the current elected "main orchestrator" should do this cleanup - given that client apps should only be related to it

**Comment by juditnovak** [comment]
Shortly: the request is to support manually created users.
