### ISSUE TITLE
Use all DNS names and ip addresses again as Subject Alternative Names (related to upstream bug #4480)

### ISSUE THREAD

**Issue by reneradoi** [canonical/opensearch-operator#382]
With https://github.com/canonical/opensearch-operator/pull/380 the `Subject Alternative Names` in the certificates were reduced to only one DNS name and one ip address. This is to mitigate the impact of upstream Opensearch bug https://github.com/opensearch-project/security/issues/4480, which causes failure when reloading TLS certificates via API.

Once the upstream bug is removed, the function `_get_sans()` in `opensearch_tls.py` should be adjusted again to the original set of DNS names and ip addresses in the sans-dictionary.

**Comment by phvalguima** [comment]
Fixed by https://github.com/canonical/opensearch-operator/commit/a887c2b2de909cd73b67a8e87843fe929dba4b15
