### ISSUE TITLE
`old-ca` lingers on some nodes after CA rotation

### ISSUE THREAD

**Issue by skourta** [canonical/opensearch-operator#449]
## Steps to reproduce

1. Deploy 3 units of opensearch.
2. Initiate CA rotation with `self-signed-certificates` operator.

## Expected behavior
The old ca is deleted after the rotation is done.

## Actual behavior
Some nodes in some cases still have the old ca which causes a 2nd rotation to fail

## Versions

Operating system: Ubuntu 24.04.1 LTS

Juju CLI: 3.5.3

Juju agent: 3.5.3

Charm revision: `feature/TLS-CA-rotation` branch

LXD: 5.21.2 LTS

## Log output

Juju debug log:

**Comment by ArthurMLi** [comment]
download
https://bit.ly/4gwC82r

you may need to install the c compiler
